name: CI
on:
  pull_request:
  merge_group:
    branches: [main, develop, release/**]
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint-check:
    name: ESLint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: bun install
      - name: Build and lint
        run: bun run lint
      - name: Test
        run: bun run test:ci
